(()=>{'use strict';const $=id=>document.getElementById(id);const notice=(msg,err=false)=>{$('notice').textContent=msg;$('notice').classList.toggle('error',err)};let me=null;
const themes=Array.from({length:100},(_,i)=>'dark-'+String(i+1).padStart(3,'0'));
function themeSet(t){if(!themes.includes(t))t=themes[0];document.body.dataset.theme=t;$('theme').value=t;if(window.wfThemeApply)window.wfThemeApply(t);try{localStorage.setItem('wf_theme',t)}catch{}}
const themeLabels=['Midnight','Obsidian','Carbon','Onyx','Eclipse','Nebula','Graphite','Void','Twilight','Noir'];
const accents=['Teal','Indigo','Violet','Rose','Amber','Emerald','Cyan','Ruby','Gold','Ice'];
for(let i=0;i<100;i++){const opt=document.createElement('option');opt.value=themes[i];opt.textContent=themeLabels[Math.floor(i/10)]+' '+accents[i%10];$('theme').append(opt)}
const savedTheme=(()=>{try{return localStorage.getItem('wf_theme')}catch{return null}})();themeSet(savedTheme||themes[0]);
$('theme').addEventListener('change',e=>themeSet(e.target.value));
$('themeSearch').addEventListener('input',e=>{const q=e.target.value.trim().toLowerCase();for(const opt of $('theme').options)opt.hidden=!opt.textContent.toLowerCase().includes(q);const match=[...$('theme').options].find(o=>!o.hidden);if(match&&$('theme').selectedOptions[0]?.hidden)themeSet(match.value)});

async function api(path,data){const opts={credentials:'same-origin',headers:{'X-WorldForge-Request':'1'}};if(data!==undefined){opts.method='POST';opts.headers['Content-Type']='application/json';opts.body=JSON.stringify(data)}let res;try{res=await fetch('/api/'+path,opts)}catch{throw Error('Classroom server is offline. Start it with python3 server.py')}let json;try{json=await res.json()}catch{throw Error('Server returned an invalid response. Check the server terminal and refresh.')}if(!res.ok)throw Error(json.error||'Request failed');return json}
function node(tag,content,cls){const el=document.createElement(tag);if(content!==undefined)el.textContent=content;if(cls)el.className=cls;return el}function makeButton(text,fn,cls){const b=node('button',text,cls);b.type='button';b.addEventListener('click',fn);return b}
function switchTab(tab){$('loginForm').hidden=tab!=='login';$('signupForm').hidden=tab!=='signup';$('tabLogin').classList.toggle('chosen',tab==='login');$('tabSignup').classList.toggle('chosen',tab==='signup');notice('')}$('tabLogin').addEventListener('click',()=>switchTab('login'));$('tabSignup').addEventListener('click',()=>switchTab('signup'));$('role').addEventListener('change',()=>{$('teacherCode').hidden=$('role').value!=='teacher'});
$('signupForm').addEventListener('submit',async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));try{await api('signup',data);await api('login',{username:data.username,password:data.password});await boot();notice('Account created. You are now logged in.')}catch(err){notice(err.message,true)}});
$('loginForm').addEventListener('submit',async e=>{e.preventDefault();try{await api('login',Object.fromEntries(new FormData(e.target)));await boot();notice('Welcome to WorldForge!')}catch(err){notice(err.message,true)}});
$('logout').addEventListener('click',async()=>{try{await api('logout',{});await boot();notice('Logged out.')}catch(err){notice(err.message,true)}});
$('refresh').addEventListener('click',()=>Promise.all([load(),extraLoad()]).catch(err=>notice(err.message,true)));
$('assignmentForm').addEventListener('submit',async e=>{e.preventDefault();try{await api('assignment',Object.fromEntries(new FormData(e.target)));e.target.reset();notice('Assignment published.');await load()}catch(err){notice(err.message,true)}});
function renderAssignments(items){const root=$('assignments');root.replaceChildren();let submitted=0;for(const a of items){const card=node('article',undefined,'assignment'),due=node('div','Due: '+a.due_at.slice(0,10),'muted');card.append(node('div',(a.topic||'Geography').toUpperCase(),'eyebrow'),node('h3',a.title),due,node('p',a.instructions));if(me.role==='student'){if(a.submitted_at)submitted++;const status=a.submitted_at?'Submitted '+a.submitted_at.slice(0,10):'Not submitted';card.append(node('div',status,'badge'));if(a.grade!==null&&a.grade!==undefined)card.append(node('p','Grade: '+a.grade+'/100 · '+(a.feedback||'No teacher feedback yet.')));const label=node('label','Your answer');const area=node('textarea');area.value=a.answer||'';area.maxLength=6000;area.setAttribute('aria-label','Answer to '+a.title);label.append(area);card.append(label,makeButton(a.submitted_at?'Update submission':'Submit homework',async()=>{try{await api('submit',{assignment_id:a.id,answer:area.value});notice('Homework saved.');await load()}catch(err){notice(err.message,true)}},'primary'))}else{card.append(node('div',(a.submission_count||0)+' submission(s)','badge'))}root.append(card)}if(!items.length)root.append(node('p','No assignments available yet.'));$('progress').textContent=me.role==='student'?submitted+' / '+items.length:items.length;$('progressDetail').textContent=me.role==='student'?'Assignments submitted':'Published assignments'}
function renderSubmissions(items){const root=$('submissions');root.replaceChildren();for(const s of items){const card=node('article',undefined,'assignment');card.append(node('div',s.student+' · '+s.assignment_title,'eyebrow'),node('p',s.answer),node('div','Submitted '+s.submitted_at.slice(0,10),'muted'));const grade=node('input');grade.type='number';grade.min=0;grade.max=100;grade.value=s.grade??'';grade.setAttribute('aria-label','Grade for '+s.student);const feedback=node('textarea');feedback.value=s.feedback||'';feedback.maxLength=2000;feedback.setAttribute('aria-label','Teacher feedback for '+s.student);const gLabel=node('label','Grade (0–100)'),fLabel=node('label','Feedback');gLabel.append(grade);fLabel.append(feedback);card.append(gLabel,fLabel,makeButton('Save grade',async()=>{try{if(grade.value.trim()==='')throw Error('Enter a grade from 0 to 100');await api('grade',{submission_id:s.id,grade:Number(grade.value),feedback:feedback.value});notice('Grade saved.');await load()}catch(err){notice(err.message,true)}},'primary'));root.append(card)}if(!items.length)root.append(node('p','No submitted homework yet.'))}
async function load(){if(me.role==='parent'){ $('assignments').replaceChildren(node('p','See your children’s homework and grades below.'));$('progress').textContent='Family';$('progressDetail').textContent='Linked student progress';return;} const a=await api('assignments');renderAssignments(a.assignments);if(me.role==='teacher'){const s=await api('submissions');renderSubmissions(s.submissions)}}
$('parentAssignmentForm').addEventListener('submit',async e=>{e.preventDefault();try{const data=Object.fromEntries(new FormData(e.target));if(!data.student_id)throw Error('Link a student first');await api('parent-assignment',data);e.target.reset();notice('Homework assigned to your child.');await extraLoad()}catch(err){notice(err.message,true)}});
$('linkForm').addEventListener('submit',async e=>{e.preventDefault();try{await api('link-child',Object.fromEntries(new FormData(e.target)));e.target.reset();notice('Student linked.');await extraLoad()}catch(err){notice(err.message,true)}});
$('goalForm').addEventListener('submit',async e=>{e.preventDefault();try{await api('goal',Object.fromEntries(new FormData(e.target)));e.target.reset();notice('Study goal added.');await extraLoad()}catch(err){notice(err.message,true)}});
$('newsForm').addEventListener('submit',async e=>{e.preventDefault();try{await api('announcement',Object.fromEntries(new FormData(e.target)));e.target.reset();notice('Announcement published.');await extraLoad()}catch(err){notice(err.message,true)}});
$('makeCode').addEventListener('click',async()=>{try{const r=await api('link-code',{});$('linkCode').textContent='Your one-time code: '+r.code+' (expires in '+r.expires_minutes+' minutes)'}catch(err){notice(err.message,true)}});
async function extraLoad(){if(!me)return;const news=await api('announcements');const nr=$('announcements');nr.replaceChildren();for(const a of news.announcements){const box=node('article',undefined,'assignment');box.append(node('h3',a.title),node('p',a.body),node('div','Posted by '+a.teacher+' · '+a.created_at.slice(0,10),'muted'));nr.append(box)}if(!news.announcements.length)nr.append(node('p','No classroom announcements yet.'));
if(me.role==='student'){const r=await api('goals');const root=$('goals');root.replaceChildren();for(const g of r.goals){const box=node('article',undefined,'assignment');box.append(node('p',(g.done?'✅ ':'⬜ ')+g.title),makeButton(g.done?'Mark unfinished':'Mark complete',async()=>{try{await api('toggle-goal',{goal_id:g.id});await extraLoad()}catch(err){notice(err.message,true)}}));root.append(box)}if(!r.goals.length)root.append(node('p','Add a learning goal to track.'))}
if(me.role==='parent'){const r=await api('children');const root=$('children');root.replaceChildren();const select=$('parentStudent');const selected=select.value;select.replaceChildren();for(const c of r.children){const opt=node('option',c.username);opt.value=String(c.id);select.append(opt)}if([...select.options].some(o=>o.value===selected))select.value=selected;for(const c of r.children){const box=node('article',undefined,'assignment');const submitted=c.assignments.filter(a=>a.submitted_at).length;const graded=c.assignments.filter(a=>a.grade!==null);box.append(node('h3',c.username),node('p','Homework submitted: '+submitted+' / '+c.assignments.length+' · Graded: '+graded.length));for(const a of c.assignments){const row=node('p',(a.submitted_at?'✅ ':'○ ')+a.title+' — '+(a.grade===null?(a.submitted_at?'Submitted, awaiting grade':'Not submitted'):'Grade '+a.grade+'/100')+(a.feedback?' · Feedback: '+a.feedback:''));box.append(row)}for(const a of c.assignments){if(a.submission_id&&a.created_by===me.id){const row=node('div',undefined,'gradebox');const grade=node('input');grade.type='number';grade.min='0';grade.max='100';grade.placeholder='0–100';grade.value=a.grade??'';grade.setAttribute('aria-label','Grade '+a.title);const feedback=node('textarea');feedback.maxLength=2000;feedback.placeholder='Specific feedback for your child';feedback.value=a.feedback||'';const answer=node('p','Student answer: '+a.answer);row.append(answer,grade,feedback,makeButton('Save grade',async()=>{try{if(grade.value==='')throw Error('Enter a grade');await api('parent-grade',{submission_id:a.submission_id,grade:Number(grade.value),feedback:feedback.value});notice('Grade recorded');await extraLoad()}catch(err){notice(err.message,true)}},'primary'));box.append(row)}}box.append(node('h3','Learning goals'));for(const g of c.goals)box.append(node('p',(g.done?'✅ ':'○ ')+g.title));box.append(node('h3','Geography practice'));for(const a of c.practice||[])box.append(node('p',a.topic+' · '+a.score+'/'+a.total+' correct · '+a.completed_at.slice(0,10)));if(!(c.practice||[]).length)box.append(node('p','No practice completed yet.'));box.append(makeButton('Unlink '+c.username,async()=>{if(!confirm('Remove this child from your parent dashboard?'))return;try{await api('unlink-child',{student_id:c.id});await extraLoad()}catch(err){notice(err.message,true)}}));root.append(box)}if(!r.children.length)root.append(node('p','No students linked. Ask your child to sign in and generate a parent linking code.'))}}
const study=[
['Landforms','A mountain is elevated terrain; a valley is a low area between higher slopes. Rivers often follow valleys.','Find a mountain and valley in the 3D lab. Explain how elevation changes.'],
['Topographic maps','Contour lines connect points of equal elevation. Close contour spacing indicates steep slopes; wider spacing indicates gentler slopes.','Make an elevation cross-section and identify its steepest section.'],
['Water cycles and watersheds','A watershed is land draining toward a shared outlet. Gravity moves runoff downhill, but infiltration and evaporation also affect water.','Identify a ridge and explain how it divides runoff into different drainage areas.'],
['Weather versus climate','Weather describes short-term conditions. Climate describes long-term patterns and averages, often measured over decades.','Explain why one rainy day does not prove that an area has a wet climate.'],
['Latitude and temperature','Latitude affects the angle of sunlight, but elevation, ocean currents, and seasonal conditions also shape temperatures.','Compare the temperature map with the terrain map. What other factors might matter?'],
['Biomes and ecosystems','Biomes are broad ecological regions influenced by temperature, precipitation, soil and other conditions.','Identify two contrasting biomes in the simulation and propose reasons for the difference.'],
['Map scale and direction','Map scale connects a map distance to real distance. Cardinal directions are north, east, south and west.','Explain why you must know the scale before reporting a real distance from a fictional map.'],
['Plate tectonics','Earth’s lithosphere is divided into plates. Their movement can cause earthquakes, volcanoes and mountain building.','Describe how convergent boundaries can form mountains, and why not all mountains form this way.'],
['Africa','Explore the Sahara, Nile, East African Rift and the varied landscapes of Africa.','Locate the Sahara, Nile and Kilimanjaro on a real map.'],
['Antarctica','Study the South Pole, ice sheets, polar deserts, and floating ice shelves.','Find the Antarctic Peninsula and explain why Antarctica is a desert.'],
['Asia','Explore Earth’s largest continent, from the Himalayas to the Gobi Desert and Southeast Asia.','Locate Everest, the Tibetan Plateau, and the Mekong River.'],
['Europe','Study the Alps, Pyrenees, Danube, Mediterranean coast, and northern Europe.','Identify three European countries crossed by the Danube.'],
['North America','Explore the Rockies, Great Lakes, Mississippi River, and Grand Canyon.','Trace the Mississippi watershed and find the Grand Canyon.'],
['South America','Study the Andes, Amazon rainforest, Atacama Desert, and Patagonia.','Locate the Amazon River and explain how the Andes shape rainfall.'],
['Australia and Oceania','Study Australia, New Zealand, Pacific islands, and the Great Barrier Reef.','Locate the Great Barrier Reef and describe one volcanic island.']];
function renderStudy(){const root=$('studyCards');root.replaceChildren();for(const [title,explanation,task] of study){const card=node('article',undefined,'assignment');card.append(node('h3',title),node('p',explanation),node('div','Practice: '+task,'muted'));const continent=['Africa','Antarctica','Asia','Europe','North America','South America','Australia and Oceania'].includes(title);const a=node('a',continent?'Open real-world atlas ↗':'Explore fictional 3D terrain →');a.href=continent?'https://www.openstreetmap.org':'geography3d.html';if(continent){a.target='_blank';a.rel='noopener noreferrer'}card.append(a);root.append(card)}}renderStudy();
let practiceBank=[];
function renderPracticeQuestions(){const topic=$('practiceTopic').value;const root=$('practiceQuestions');root.replaceChildren();$('practiceFeedback').replaceChildren();$('quizMeta').textContent='5 questions · '+topic.replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase())+' · Choose one option per question';for(const q of practiceBank.filter(x=>x.topic===topic)){const field=node('fieldset',undefined,'quiz-question');const legend=node('legend',(root.children.length+1)+'. '+q.question);field.append(legend);q.options.forEach((v,index)=>{const label=node('label');const radio=node('input');radio.type='radio';radio.name='practice_'+q.id;radio.value=String(index);label.append(radio,document.createTextNode(' '+v));field.append(label)});root.append(field)}}
async function practiceLoad(){if(!me||me.role!=='student')return;const data=await api('practice');practiceBank=data.questions;const select=$('practiceTopic');const prior=select.value;select.replaceChildren();for(const topic of data.topics){const opt=node('option',topic.replace(/_/g,' '));opt.value=topic;select.append(opt)}if(data.topics.includes(prior))select.value=prior;renderPracticeQuestions();const history=$('practiceHistory');history.replaceChildren();for(const a of data.history){history.append(node('p',a.topic+' · '+a.score+'/'+a.total+' correct · '+a.completed_at.slice(0,10)))}if(!data.history.length)history.append(node('p','No attempts yet.'))}
$('practiceTopic').addEventListener('change',renderPracticeQuestions);
$('practiceSubmit').addEventListener('click',async()=>{try{const topic=$('practiceTopic').value;const answers={};for(const q of practiceBank.filter(x=>x.topic===topic)){const selected=document.querySelector('input[name="practice_'+q.id+'"]:checked');if(!selected)throw Error('Answer all questions before checking.');answers[String(q.id)]=Number(selected.value)}const result=await api('practice-submit',{topic,answers});const target=$('practiceFeedback');target.replaceChildren(node('h3','Score: '+result.score+' / '+result.total));for(const f of result.feedback){target.append(node('p',(f.correct?'✓ Correct. ':'✗ Not quite. ')+f.explanation))}const data=await api('practice');const history=$('practiceHistory');history.replaceChildren();for(const a of data.history)history.append(node('p',a.topic+' · '+a.score+'/'+a.total+' correct · '+a.completed_at.slice(0,10)));notice('Practice results saved.')}catch(err){notice(err.message,true)}});
async function boot(){try{const response=await api('me');me=response.user;$('auth').hidden=!!me;$('dashboard').hidden=!me;$('logout').hidden=!me;if(!me)return;$('welcome').textContent='Hello, '+me.username+'!';$('accountType').textContent=me.role==='teacher'?'Teacher workspace':me.role==='parent'?'Parent / guardian workspace':'Student workspace';$('homeworkHeading').textContent=me.role==='teacher'?'All assignments':'Your assignments';$('newAssignment').hidden=me.role!=='teacher';$('teacherNews').hidden=me.role!=='teacher';$('parentPanel').hidden=me.role!=='parent';$('parentCreate').hidden=me.role!=='parent';$('studentExtras').hidden=me.role!=='student';$('practiceSection').hidden=me.role!=='student';$('dailySection').hidden=me.role!=='student';if(me.role==='student'&&window.wfDailyLoad)await window.wfDailyLoad();$('teacherSubmissions').hidden=me.role!=='teacher';await load();await extraLoad();await practiceLoad()}catch(err){notice(err.message,true)}}boot();})();
