(()=>{'use strict';
const $=id=>document.getElementById(id);
const facts=[
['continents','Asia','Asia is the largest continent by land area.','Which continent has the greatest land area?'],
['continents','Africa','Africa is crossed by the equator and the Tropics of Cancer and Capricorn.','Which major latitude lines cross Africa?'],
['continents','North America','The Rocky Mountains form an extensive mountain system in western North America.','Where are the Rocky Mountains?'],
['continents','South America','The Andes extend along western South America.','Which mountain system runs along western South America?'],
['continents','Antarctica','Antarctica is the coldest continent and is covered largely by an ice sheet.','Why is Antarctica considered a polar desert?'],
['continents','Europe','The Alps extend across several countries in central and southern Europe.','Name a European country crossed by the Alps.'],
['continents','Australia and Oceania','Australia is the smallest continent in the seven-continent model; Oceania also includes many Pacific islands.','How do Australia and Oceania differ?'],
['water','Pacific Ocean','The Pacific is the largest ocean by surface area.','Which is the largest ocean?'],
['water','Atlantic Ocean','The Mid-Atlantic Ridge marks a major divergent plate boundary.','What happens at a divergent plate boundary?'],
['water','Indian Ocean','The Indian Ocean lies between Africa, Asia, Australia, and the Southern Ocean.','Which continents border the Indian Ocean?'],
['water','Southern Ocean','The Southern Ocean encircles Antarctica.','Which continent does the Southern Ocean surround?'],
['water','Arctic Ocean','The Arctic Ocean occupies the region around the North Pole.','Which ocean contains the North Pole region?'],
['water','Nile River','The Nile flows generally north through northeastern Africa to the Mediterranean Sea.','Which sea receives the Nile?'],
['water','Amazon River','The Amazon drains a vast basin in tropical South America.','Why is a drainage basin important?'],
['water','Mississippi River','The Mississippi River system drains much of central North America into the Gulf of Mexico.','Where does the Mississippi flow into the sea?'],
['land','Mount Everest','Mount Everest lies in the Himalayas on the Nepal–China border.','Which mountain range contains Everest?'],
['land','Sahara','The Sahara is a vast hot desert in northern Africa.','Where is the Sahara located?'],
['land','Grand Canyon','The Colorado River and erosion shaped the Grand Canyon over millions of years.','What process helped form the Grand Canyon?'],
['land','Himalayas','The Himalayas arose through convergence between the Indian and Eurasian tectonic plates.','Which plate movement builds large mountains?'],
['land','East African Rift','The East African Rift is an active zone of continental extension.','What happens to Earth’s crust at a rift?'],
['land','Atacama Desert','The Atacama lies along the Pacific side of South America and has exceptionally arid areas.','Which continent contains the Atacama?'],
['climate','Weather vs climate','Weather describes short-term conditions; climate describes patterns over decades.','What is the difference between weather and climate?'],
['climate','Rain shadow','Mountains can force moist air upward, leaving the leeward side drier.','Which side of a mountain can be drier?'],
['climate','Tropical rainforest','Tropical rainforests typically receive abundant rainfall and have high biodiversity.','Why does rainfall matter for vegetation?'],
['climate','Tundra','Tundra environments have short growing seasons; permafrost is common in many tundra regions.','What is permafrost?'],
['climate','Monsoon','Monsoons are seasonal wind changes often linked with major shifts in precipitation.','How can monsoons affect farming?'],
['maps','Equator','The equator is 0° latitude and divides Earth into Northern and Southern Hemispheres.','What is the latitude of the equator?'],
['maps','Prime meridian','The prime meridian is the reference line for 0° longitude.','What does longitude measure?'],
['maps','Contour lines','Contour lines connect points of equal elevation on a map.','What do closely spaced contour lines indicate?'],
['maps','Map scale','Scale relates distance shown on a map to real-world ground distance.','How do you measure real distance on a map?'],
['maps','Plate tectonics','Earth’s lithosphere is divided into plates that move relative to one another.','How do tectonic plates affect landforms?'],
];
const units={
continents:[['Seven continents','List all seven continents.','Circle the continent with the largest land area.','Name a major mountain range on three continents.','Describe two differences between Antarctica and Africa.','Choose a continent you would like to visit and explain why.'],['Compare two continents','Name two continents you want to compare.','Compare their approximate locations and climates.','Name one river or mountain range in each.','Explain how latitude might influence their climates.','Describe one cultural or environmental question you would research next.']],
maps:[['Latitude and longitude','What is latitude?','What is longitude?','What coordinates describe the equator and prime meridian crossing?','How can coordinates help rescuers locate a place?','Sketch a globe showing both reference lines.'],['Map reading','Explain the purpose of a map legend.','How does a scale bar help?','What does a compass rose show?','What do close contour lines indicate?','Describe how you would plan a route using a map.']],
physical:[['Mountains and valleys','How does a mountain differ from a hill?','What is a valley?','Describe how a river can shape a valley.','What is erosion?','Compare a steep slope with a gentle slope.'],['Rivers and watersheds','Define watershed.','Where does water flow in relation to elevation?','How do tributaries connect to a main river?','Explain how human activity can affect downstream water quality.','Sketch a drainage basin showing a ridge and stream.']],
climate:[['Weather and climate','Define weather.','Define climate.','List three factors that influence local climate.','Explain the rain-shadow effect.','Why might coastal areas have milder temperatures?'],['Biomes and adaptation','Name four major land biomes.','Why are rainforests generally humid?','Explain permafrost.','How can animals adapt to deserts?','How might a biome shift if precipitation decreases?']],
projects:[['Build an atlas page','Choose a country and identify its continent.','Draw its approximate shape and mark north.','Label its capital and two major physical features.','Describe its climate using a reliable reference.','Write three questions someone could ask about your atlas page.'],['Field geography observation','Choose a safe outdoor location to observe.','Record the date and describe the weather.','Describe the slope, soil, plants, or nearby water you can observe.','Draw a simple map with a north arrow and legend.','Describe how rainfall might travel across the location.']]
};
let group='continents',worksheet=0;
function renderSheet(){const list=units[group];$('worksheetChoice').replaceChildren(...list.map((w,i)=>{const o=document.createElement('option');o.value=i;o.textContent=w[0];return o}));$('worksheetChoice').value=String(worksheet);const w=list[worksheet],root=$('worksheetContent');root.replaceChildren();const h=document.createElement('h3');h.textContent=w[0];root.append(h);const meta=document.createElement('p');meta.textContent='Name: '+($('worksheetStudent').value.trim()||'________________')+'     Date: _______________';root.append(meta);w.slice(1).forEach((q,i)=>{const label=document.createElement('label');label.textContent=(i+1)+'. '+q;const area=document.createElement('textarea');area.rows=3;area.maxLength=3000;area.dataset.index=String(i);area.setAttribute('aria-label','Answer '+(i+1));label.append(area);root.append(label)});}
document.querySelectorAll('[data-unit]').forEach(b=>b.addEventListener('click',()=>{group=b.dataset.unit;worksheet=0;document.querySelectorAll('[data-unit]').forEach(x=>x.classList.toggle('active',x===b));renderSheet()}));$('worksheetChoice').addEventListener('change',e=>{worksheet=Number(e.target.value)||0;renderSheet()});$('worksheetStudent').addEventListener('change',()=>{const meta=$('worksheetContent').querySelector('p');if(meta)meta.textContent='Name: '+($('worksheetStudent').value.trim()||'________________')+'     Date: _______________'});$('worksheetPrint').addEventListener('click',()=>window.print());$('worksheetClear').addEventListener('click',()=>{$('worksheetContent').querySelectorAll('textarea').forEach(a=>a.value='')});
function renderFacts(){const cat=$('factCategory').value,search=$('factSearch').value.toLowerCase().trim(),root=$('factResults');root.replaceChildren();const found=facts.filter(f=>(cat==='all'||f[0]===cat)&&(!search||f.join(' ').toLowerCase().includes(search)));found.forEach(f=>{const card=document.createElement('article');card.className='fact-card';const tag=document.createElement('small');tag.textContent=f[0].toUpperCase();const title=document.createElement('h3');title.textContent=f[1];const desc=document.createElement('p');desc.textContent=f[2];const question=document.createElement('p');question.className='fact-question';question.textContent='Think about it: '+f[3];card.append(tag,title,desc,question);root.append(card)});$('factCount').textContent=found.length+' of '+facts.length+' geography facts';if(!found.length)root.textContent='No facts matched your search.';}
$('factCategory').addEventListener('change',renderFacts);$('factSearch').addEventListener('input',renderFacts);
let index=0,known=0,seen=0;function drawFlash(){const f=facts[index];$('flashPrompt').textContent=f[1]+' — explain this geographic feature or term.';$('flashAnswer').textContent=f[2];$('flashAnswer').hidden=true;$('flashStats').textContent='Card '+(index+1)+' / '+facts.length+' · Remembered '+known+' / '+seen;$('flashReveal').disabled=false;}
$('flashReveal').addEventListener('click',()=>{$('flashAnswer').hidden=false});function advance(didKnow){seen++;if(didKnow)known++;index=(index+1)%facts.length;drawFlash()}$('flashAgain').addEventListener('click',()=>advance(false));$('flashKnow').addEventListener('click',()=>advance(true));$('flashReset').addEventListener('click',()=>{index=known=seen=0;drawFlash()});
$('worksheetAssign').addEventListener('click',()=>{const form=document.getElementById('parentAssignmentForm');if(form.hidden){return;}const w=units[group][worksheet];form.elements.title.value=w[0];form.elements.topic.value=group;form.elements.instructions.value=w.slice(1).map((s,i)=>(i+1)+'. '+s).join('\n');form.scrollIntoView({behavior:'smooth'});});
new MutationObserver(()=>{$('worksheetAssign').hidden=document.getElementById('parentCreate').hidden}).observe(document.getElementById('parentCreate'),{attributes:true,attributeFilter:['hidden']});$('worksheetAssign').hidden=document.getElementById('parentCreate').hidden;
renderSheet();renderFacts();drawFlash();
})();