// WorldForge V11 dark theme palette + server-scored daily progression
(()=>{'use strict';
const $=id=>document.getElementById(id);
const names=['Midnight','Obsidian','Carbon','Onyx','Eclipse','Nebula','Graphite','Void','Twilight','Noir'];
const accents=['Teal','Indigo','Violet','Rose','Amber','Emerald','Cyan','Ruby','Gold','Ice'];
window.wfThemeApply=function(theme){let i=parseInt(theme.split('-')[1],10)-1;if(!Number.isInteger(i)||i<0||i>=100)i=0;const group=Math.floor(i/10), variation=i%10,hue=[170,236,275,330,40,145,194,355,48,205][variation];const bgHue=[218,225,210,230,245,268,220,200,235,210][group];let light=7+group%4;const styles=document.documentElement.style;styles.setProperty('--bg',`hsl(${bgHue} 27% ${light}%)`);styles.setProperty('--card',`hsl(${bgHue} 26% ${light+5}%)`);styles.setProperty('--text','#f1f5fc');styles.setProperty('--muted','#b1bdd0');styles.setProperty('--edge',`hsl(${bgHue} 21% ${light+16}%)`);styles.setProperty('--accent',`hsl(${hue} 88% 72%)`);styles.setProperty('--subtle',`hsl(${bgHue} 25% ${light+9}%)`);styles.setProperty('--hero',`hsl(${bgHue} 30% ${light+2}%)`);const p=$('themePreview');if(p)p.textContent=`${names[group]} ${accents[variation]} • dark palette ${i+1} of 100`};
window.wfThemeApply(document.body.dataset.theme||'dark-001');
let daily=null;
async function req(route,payload){const response=await fetch('/api/'+route,{credentials:'same-origin',method:payload?'POST':'GET',headers:payload?{'Content-Type':'application/json'}:{},body:payload?JSON.stringify(payload):undefined});let data;try{data=await response.json()}catch{throw Error('Unable to reach classroom server')}if(!response.ok)throw Error(data.error||'Request failed');return data}
window.wfDailyLoad=async()=>{const target=$('dailyQuestions');if(!target)return;try{daily=await req('daily');$('dailyStats').textContent=`Day ${daily.day} · Difficulty ${daily.difficulty}/16 · ${daily.total} questions · ${daily.topic_count} subject areas · 🔥 ${daily.streak}-day streak`;
target.replaceChildren();$('dailyFeedback').replaceChildren();$('dailySubmit').hidden=!!daily.completed;
if(daily.completed){target.textContent=`Today's mission complete: ${daily.completed.score}/${daily.completed.total}. A new mission unlocks tomorrow (UTC).`}
else for(let n=0;n<daily.questions.length;n++){const q=daily.questions[n],box=document.createElement('fieldset'),legend=document.createElement('legend');box.className='quiz-question';legend.textContent=`${n+1}. [${q.topic}] ${q.question}`;box.append(legend);q.options.forEach((answer,i)=>{const label=document.createElement('label'),input=document.createElement('input');input.type='radio';input.name='daily_'+q.id;input.value=String(i);label.append(input,document.createTextNode(' '+answer));box.append(label)});target.append(box)}
const history=$('dailyHistory');history.replaceChildren();for(const r of daily.history){const row=document.createElement('p');row.textContent=`${r.challenge_date} · ${r.score}/${r.total} correct`;history.append(row)}if(!daily.history.length)history.textContent='Complete your first daily mission to start your history.';
}catch(err){$('dailyStats').textContent=err.message}};
$('dailySubmit')?.addEventListener('click',async()=>{if(!daily||daily.completed)return;const answers={};for(const q of daily.questions){const selected=document.querySelector(`input[name="daily_${q.id}"]:checked`);if(!selected){$('dailyFeedback').textContent='Answer all questions before submitting.';return}answers[q.id]=Number(selected.value)}try{const r=await req('daily-submit',{answers});$('dailyFeedback').replaceChildren();const heading=document.createElement('h3');heading.textContent=`Score: ${r.score}/${r.total}`;$('dailyFeedback').append(heading);for(const f of r.feedback){const p=document.createElement('p');p.textContent=(f.correct?'✓ ':'✗ ')+f.explanation;$('dailyFeedback').append(p)}await window.wfDailyLoad();$('dailyFeedback').replaceChildren(heading);for(const f of r.feedback){const p=document.createElement('p');p.textContent=(f.correct?'✓ ':'✗ ')+f.explanation;$('dailyFeedback').append(p)}}catch(err){$('dailyFeedback').textContent=err.message}});
})();