(()=>{'use strict';
const $=id=>document.getElementById(id);const body=document.body;
const update=()=>{let signed=!$('dashboard').hidden;body.classList.toggle('wf-guest',!signed);body.classList.toggle('wf-signed',signed);body.classList.add('wf-ready');};
const observer=new MutationObserver(update);observer.observe($('dashboard'),{attributes:true,attributeFilter:['hidden']});update();
const dlg=$('paletteDialog'),grid=$('paletteGrid');const names=['Midnight','Obsidian','Carbon','Onyx','Eclipse','Nebula','Graphite','Void','Twilight','Noir'];const accents=['Teal','Emerald','Violet','Ruby','Amber','Cyan','Rose','Gold','Blue','Lime'];const bgHue=[216,255,210,220,280,245,225,260,200,235];const accentHue=[173,141,275,350,39,191,325,46,217,93];
const swatches=Array.from({length:100},(_,i)=>{const g=Math.floor(i/10),v=i%10;return {id:'dark-'+String(i+1).padStart(3,'0'),title:names[g]+' '+accents[v],bg:`hsl(${bgHue[g]} 30% ${7+g%3}%)`,accent:`hsl(${accentHue[v]} 88% 72%)`}});
function render(filter=''){grid.replaceChildren();for(const item of swatches.filter(x=>x.title.toLowerCase().includes(filter.toLowerCase()))){const btn=document.createElement('button');btn.type='button';btn.className='palette-choice';btn.setAttribute('aria-pressed',String(body.dataset.theme===item.id));const sample=document.createElement('span');sample.className='palette-sample';sample.style.background=`linear-gradient(135deg,${item.bg},hsl(${accentHue[(Number(item.id.slice(-3))-1)%10]} 60% 21%))`;sample.style.setProperty('--sample-accent',item.accent);const caption=document.createElement('small');caption.textContent=item.title;btn.append(sample,caption);btn.addEventListener('click',()=>{const select=$('theme');select.value=item.id;select.dispatchEvent(new Event('change',{bubbles:true}));render($('paletteSearch').value)});grid.append(btn)}if(!grid.children.length){const p=document.createElement('p');p.textContent='No matching themes';grid.append(p)}}
const open=()=>{dlg.hidden=false;render();$('paletteSearch').focus()};const close=()=>{dlg.hidden=true;($('sidebarPalette')&&body.classList.contains('wf-signed')?$('sidebarPalette'):$('openPalette')).focus()};$('openPalette')?.addEventListener('click',open);$('sidebarPalette')?.addEventListener('click',open);$('closePalette')?.addEventListener('click',close);$('paletteSearch')?.addEventListener('input',e=>render(e.target.value));dlg?.addEventListener('click',e=>{if(e.target===dlg)close()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!dlg.hidden)close()});
const links=[...document.querySelectorAll('.workspace-sidebar a')];links.forEach(a=>a.addEventListener('click',()=>{links.forEach(x=>x.classList.toggle('active',x===a))}));
})();